name: smart-traffic-ppo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - matplotlib
  - gymnasium
  - pip:
      - torch
      - sumo-rl
      - traci
      - requests
